package com.sarvesh14.notifyme

object Constants {


    const val ACTION_START_OR_RESUME_SERVICE = "ACTION_START_OR_RESUME_SERVICE"
    const val ACTION_PAUSE_SERVICE = "ACTION_PAUSE_SERVICE"
    const val ACTION_STOP_SERVICE = "ACTION_STOP_SERVICE"
    const val ACTION_MUTE_SERVICE = "ACTION_MUTE_SERVICE"
    const val ACTION_UNMUTE_SERVICE = "ACTION_UNMUTE_SERVICE"
    const val ACTION_CHANGE_LANGUAGE = "ACTION_CHANGE_LANGUAGE"
    const val ACTION_PLAY_NOTIFICATION = "ACTION_PLAY_NOTIFICATION"

    const val NOTIFICATION_CHANNEL_ID = "listener_channel"
    const val NOTIFICATION_CHANNEL_NAME = "Listener"
    const val NOTIFICATION_ID = 1

    const val  ACTION_SHOW_MAIN_ACTIVITY = "ACTION_SHOW_MAIN_ACTIVITY"

}